jobs:
  build:
    docker: 
      - image: cimg/node:14.5.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: npm install # install package
      - run: npm run build # install package
  test:
    docker: 
      - image: cimg/node:14.5.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install # install package
      - run: npm test # load tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test